### ISSUE TITLE
TODO: Generate benchmark plots with IP shocks

### ISSUE THREAD

**Issue by KCollins** [KCollins/magplots#34]
(Note: This is not an issue with the magplots package, but a todo list item for my postdoc work.)

Most of my test cases to date have been with HSJs, but IP shocks are a more drastic and visible event. 
- [ ] Identify event list
- [ ] Include in example code
- [ ] Possibly use as default event in functions
