### ISSUE TITLE
TODO: HSJ Event Selection

### ISSUE THREAD

**Issue by KCollins** [KCollins/magplots#35]
(Note: This is a todo item for my postdoc work, not an actual issue in magplots.)

Examine biggest dynamic pressure values in dataset; try these and see if I get a negative result. 
 - [X] Export table of selected events using df.to_markdown() and put it here to make it easier to keep track.
 
 | Max                 |   Jet Number | Ref Spacecraft   | Start               | End                 |   SM_LAT |   SM_LON |     SM_X |    SM_Y |      SM_Z |   GEO_X_1 |   GEO_Y_1 |    GEO_Z_1 |   DIST_FROM_P93_BOW_SHOCK |   DIST_FROM_MAGNETOPAUSE |   DIST_FROM_T95_NS |   L_VALUE |   INVAR_LAT |   MAGNETIC_STRENGTH |   Dynamic Pressure (nPa) |   Electron density |         Vx |          Vy |       Vz |   Count |
|:--------------------|-------------:|:-----------------|:--------------------|:--------------------|---------:|---------:|---------:|--------:|----------:|----------:|----------:|-----------:|--------------------------:|-------------------------:|-------------------:|----------:|------------:|--------------------:|-------------------------:|-------------------:|-----------:|------------:|---------:|--------:|
| 2015-04-05 19:14:46 |          261 | A                | 2015-04-05 19:14:39 | 2015-04-05 19:15:09 | 20.9746  |  15.3663 |  9.29268 | 2.55375 |  3.69447  | -0.480458 | -10.097   |  2.08439   |                  -4.27286 |                -0.623951 |             -1e+31 |   11.8379 |     73.1034 |             59.5534 |                  3.85989 |         31.3699    | -199.561   |  321.878    |  62.681  |       0 |
| 2018-09-02 07:43:18 |          238 | A                | 2018-09-02 07:43:14 | 2018-09-02 07:44:02 | -3.46162 |  10.9974 | 11.128   | 2.16252 | -0.685727 |  2.85547  |  10.9546  |  0.906536  |                  -3.12188 |                 0.414341 |             -1e+31 |   11.3984 |     72.7708 |             -1e+31  |                 32.9766  |          0.0657097 |    5.40439 |    0.108232 |  13.4919 |       0 |
| 2016-06-13 03:19:36 |          661 | D                | 2016-06-13 03:19:31 | 2016-06-13 03:19:46 | -8.55624 |  11.2021 | 10.4521  | 2.06996 | -1.6031   | -8.20325  |   6.98586 | -0.0699006 |                  -4.02601 |                -0.189972 |             -1e+31 |   11.0189 |     72.4671 |             55.5471 |                  5.16873 |         29.4192    |  -60.8748  |   60.4734   | -27.3761 |       0 |
| 2018-08-26 20:01:40 |          197 | D                | 2018-08-26 20:01:33 | 2018-08-26 20:02:12 | 13.4793  |  24.6768 | 10.4923  | 4.82078 |  2.76773  | -1.32867  | -11.7568  |  1.00068   |                  -3.06219 |                 0.903307 |             -1e+31 |   12.5561 |     73.6078 |             -1e+31  |                  5.85335 |         26.7709    |  -49.3608  | -356.737    | 363.529  |       0 |

**Comment by KCollins** [comment]
Jets 295 and 238 have the highest dynamic pressure in the set. 
 - 295 is measured by THEMIS E, right as it exits the magnetosheath and goes into the solar wind, so that's probably not a good test case. 
 - 238 is measured by THEMIS A and looks like a good candidate for the symmetric case. 
 
 After that we look for asymmetric cases:
  - 197 (northern, THEMIS D) may be promising but it looks like there might be a data gap (?)
  - 261 (northern) might be a good candidate
  - 661 (southern, THEMIS D) might be a good candidate

**Comment by KCollins** [comment]
SuperMAG polar plots: https://supermag.jhuapl.edu/rBrowse/?fidelity=low&start=2015-04-05T19%3A24%3A00.000Z&step=60
Can use for quicklook plots at ground magnetometers. For events of interest, should expect to see the Greenland sector light up. (Other sectors might light up if there's other activity going on.) By default, the scale is fixed for the magnetometer vectors, but it may be useful to adjust that for the weaker jets.

**Comment by KCollins** [comment]
Jet 238: Looks good! This was in September, though, so we don't have much Antarctic data. Could still use for a case study. Might want to compare with other Antarctic magnetometers via SuperMAG. Maybe it's a TCV?
![image](https://github.com/user-attachments/assets/3d8cbe6b-e1d0-4373-bceb-481969190306)

Jet 661: Large and rapid dip in Bx appears across all mags - rapid dv/dt, relevant for GICs/geoelectric fields and probably worth reporting. We do have some waves, hard to say for sure what is caused by the jet or not.
![image](https://github.com/user-attachments/assets/7ae5915d-a3d6-463d-8a7b-8926b028c738)

**Comment by KCollins** [comment]
- [ ] Generate survey plots for each event listed here
- [ ] Generate SuperMAG survey plots for each event, save for comparison
- [ ] Pull plots from https://themis.ssl.berkeley.edu/data/themis/thg/l2/mag/secs/ (sub or complement to SuperMAG plots)
- [ ] Generate THEMIS survey plot as in Issue #26
- [ ] Stick all in PowerPoint, review in next meeting

**Comment by KCollins** [comment]
Jet 197 is in August, so it probably doesn't have data.

**Comment by KCollins** [comment]
Quicklook plot for The Big Dip after Jet 661: https://vmo.igpp.ucla.edu/data1/SECS/Southernquicklook/2016/06/13/SouthEIC20160613_033300.jpg

**Comment by KCollins** [comment]
From our discussion on 17 Sept: 

- [ ]  Replot events of interest: 11, 1031 (particularly clean), 3461 (weaker but good; rescale time domain plots), 6242 (waves beforehand). 200 is very southerly and has nice asymmetry. 

-  [ ] BUG: Why does Jet 11 show Antarctic By data but not matching Bx data?

Next steps: 
- [ ] replot time series; remove background trends with HPF or boxcar; verify same y-axis range

Background trend can be symmetric, but the waves can be opposite - filter and check. (We might consider coming up with a definition for symmetry.) 
 - [ ] Jet 3661 is a good example where the background is symmetric, but the Pc5 activity itself is asymmetric.
