### ISSUE TITLE
TODO/BUG: Jet numbers wrap around in jet list

### ISSUE THREAD

**Issue by KCollins** [KCollins/magplots#43]
The jet numbers in the table at https://zenodo.org/records/10531587 are sorted by identifying spacecraft and the numbers wrap around; i.e., "jet 11" refers to multiple jets. Since jets are indexed by jet number in the code here, this is surely generating problems....

- [ ] In jet notebook, rename 'Jet Number' column as 'Original Jet Number'.
- [ ] Replace contents of 'Jet Number' column with numerical index of jets in the table I create.
- [ ] Upload new versions to Zenodo, and include description of the change in Zenodo abstract on new dataset.
- [ ] Update references to Zenodo dataset in this notebook

**Comment by KCollins** [comment]
Note: As of now, I haven't updated the jet numbers in Zenodo. Have to consider whether that will lead to less confusion or more in the future.
